GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/64806ec0bfc9a5792d3a8485


###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Amazing Person", 
    "subscribedToChannel": "Web dev simplified"
}