GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/64806ec0bfc9a5792d3a8485


###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Veikka", 
    "subscribedToChannel": "Cat"
}

###

PATCH http://localhost:3000/subscribers/648075bc9dce9e8ba8ee84ca
Content-Type: application/json

{
    "name": "Minna", 
    "subscribedToChannel": "Yes"
}


###

DELETE http://localhost:3000/subscribers/648073c73cd992213e79bec4